W-12980682: Update groovy used at build time to 4.x
mulesoft/mule-distributions pull request #1017
Opened 2023-04-24 15:53 UTC by elrodro83

2023-04-24 16:04 UTC, asanguinetti requested changes
Formatting issue

2023-04-24 16:04 UTC, asanguinetti commented on embedded/embedded-distribution/pom.xml
> +                        	</scripts>
There seems to be a problem with tabs vs spaces here.

2023-04-24 17:37 UTC, asanguinetti approved these changes

2023-04-24 20:09 UTC, elrodro83 commented
--validate

2023-04-24 23:19 UTC, asanguinetti submitted a review, later dismissed

2023-04-27 18:00 UTC, elrodro83 commented
--validate

2023-04-27 19:53 UTC, elrodro83 commented
--validate

2023-04-27 22:06 UTC, merged