W-13137702: Modularize the embedded module
mulesoft/mule-distributions pull request #1041
Opened 2023-05-12 19:55 UTC by rbourbonnavarro

2023-05-13 01:50 UTC, rbourbonnavarro commented
--validate

2023-05-15 20:20 UTC, elrodro83 requested changes

2023-05-15 20:20 UTC, elrodro83 commented on embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/EmbeddedControllerImpl.java
> +public class EmbeddedControllerImpl implements EmbeddedController {
`EmbeddedControllerImpl` -> `DefaultEmbeddedController`

2023-05-15 20:20 UTC, elrodro83 commented on embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/EmbeddedControllerProviderImpl.java
> +public class EmbeddedControllerProviderImpl implements EmbeddedControllerProvider {
`EmbeddedControllerProviderImpl` -> `DefaultEmbeddedControllerProvider`

2023-05-16 13:47 UTC, elrodro83 submitted a review, later dismissed

2023-05-24 16:10 UTC, elrodro83 approved these changes

2023-05-24 16:13 UTC, elrodro83 approved these changes

2023-05-29 17:18 UTC, merged