W-13205329: Make the embedded container run in the module-path
mulesoft/mule-distributions pull request #1162
Opened 2023-09-18 18:25 UTC by rbourbonnavarro

2023-09-21 20:00 UTC, elrodro83 requested changes

2023-09-21 20:00 UTC, elrodro83 commented on embedded/embedded-test/src/test/resources/log4j2-custom-file.xml
> +<Configuration status="warn" name="MyApp">
why?

2023-09-21 23:34 UTC, rbourbonnavarro commented on embedded/embedded-test/src/test/resources/log4j2-custom-file.xml
> +<Configuration status="warn" name="MyApp">
It's deprecated in `log4j`.

2023-09-22 11:31 UTC, elrodro83 approved these changes

2023-09-22 13:19 UTC, merged