Isolation
mulesoft/mule-distributions pull request #1333
Opened 2024-05-21 19:22 UTC by rbourbonnavarro

2024-07-12 20:08 UTC, elrodro83 requested changes

2024-07-12 20:08 UTC, elrodro83 commented on embedded/embedded-test/tests/src/main/java/module-info.java
> - * @moduleGraph
?

2024-07-12 20:08 UTC, elrodro83 commented on embedded/embedded-test/tests/src/test/java/org/mule/runtime/module/embedded/AbstractEmbeddedTestCase.java
> +  @Parameters(name = "{0}")
`useIsolation: {0}`

2024-07-12 20:08 UTC, elrodro83 commented on embedded/embedded-test/tests/src/test/java/org/mule/runtime/module/embedded/EmbeddedLifecycleTestCase.java
> +  @Parameters(name = "{0}")
`useIsolation: {0}`

2024-07-12 21:08 UTC, rbourbonnavarro commented on embedded/embedded-test/tests/src/main/java/module-info.java
> - * @moduleGraph
Restored.

2024-07-12 21:08 UTC, rbourbonnavarro commented on embedded/embedded-test/tests/src/test/java/org/mule/runtime/module/embedded/EmbeddedLifecycleTestCase.java
> +  @Parameters(name = "{0}")
Done.

2024-07-12 21:08 UTC, rbourbonnavarro commented on embedded/embedded-test/tests/src/test/java/org/mule/runtime/module/embedded/AbstractEmbeddedTestCase.java
> +  @Parameters(name = "{0}")
Done.

2024-07-16 19:46 UTC, elrodro83 approved these changes

2024-07-16 20:02 UTC, merged