W-12277411: Expose the data about possible drops of spans
mulesoft/mule-distributions pull request #988
Opened 2023-03-03 20:55 UTC by IvanAndresFritzler

2023-03-08 15:54 UTC, fsgonz submitted a review, later dismissed

2023-03-09 17:50 UTC, sofiamorseletto requested changes

2023-03-09 17:50 UTC, sofiamorseletto commented on standalone/src/main/resources/conf/tracer-exporter.conf
> +# Export queue size. If the queue gets full, non fitting spans will be dropped along with WARNING log of the form "Export queue overflow: {} spans has been dropped."
```suggestion
# Export queue size. If the queue gets full, non fitting spans will be dropped along with a WARNING log in the form of "Export queue overflow: {} spans have been dropped."
```

2023-03-10 14:13 UTC, fsgonz approved these changes

2023-03-10 19:08 UTC, merged